const frases = [
    
    'Dia 1: A persistência é o caminho do êxito.',
    'Dia 2: A maior de todas as torres começa no solo.',
    'Dia 3: Siga os bons e aprenda com eles.',
    'Dia 4: Não importa o tamanho da montanha, ela não pode tapar o sol.',
    'Dia 5: Lamentar aquilo que não temos é desperdiçar aquilo que já possuímos.',
    'Dia 6: Sem o fogo do entusiasmo, não há o calor da vitória.',
    'Dia 7: Sorte é estar pronto quando a oportunidade vem.',
    'Dia 8: Faça pequenas coisas agora e maiores coisas lhe serão confiadas cada dia.',
    'Dia 9: O destino não é uma questão de sorte, é uma questão de escolha. Não é algo a se esperar, é algo a se conquistar.',
    'Dia 10: A sorte favorece a mente bem preparada.',
    'Dia 11: Deixe de lado as preocupações e seja feliz.',
    'Dia 12: O pessimista vê a dificuldade em cada oportunidade; O otimista vê a oportunidade em cada dificuldade.',
    'Dia 13: Muitas das grandes realizações do mundo foram feitas por homens cansados e desanimados que continuaram trabalhando.',
    'Dia 14: Ter sorte é ter a força para não se acomodar e lutar para que o fruto do seu trabalho tenha sucesso.',
    'Dia 15: Eu acredito demais na sorte. E tenho constatado que, quanto mais duro eu trabalho, mais sorte eu tenho.',
    'Dia 16: Tente a sua sorte! A vida é feita de oportunidades. O homem que vai mais longe é quase sempre aquele que tem coragem de arriscar.',
    'Dia 17: O verdadeiro homem mede a sua força, quando se defronta com o obstáculo.',
    'Dia 18: Você precisa fazer aquilo que pensa que não é capaz de fazer.',
    'Dia 19: A vida é para quem topa qualquer parada. Não para quem para em qualquer topada.',
    'Dia 20: Inspiração vem dos outros. Motivação vem de dentro de nós.',
    'Dia 21: A vida trará coisas boas se tiver paciência.',
    'Dia 22: Demonstre amor e alegria em todas as oportunidades e verá que a paz nasce dentro de si.',
    'Dia 23: Realize o obvio, pense no improvável e conquiste o impossível.',
    'Dia 24: Acredite em milagres, mas não dependa deles.',
    'Dia 25: Nós somos o que pensamos.',
    'Dia 26: O sucesso não ocorre por acaso.',
    'Dia 27: Talento é dom, é graça. E sucesso nada tem a ver com sorte, mas com determinação e trabalho.',
    'Dia 28: Boa sorte é o que acontece quando a oportunidade encontra o planejamento.',
    'Dia 29: A arte de vencer se aprende nas derrotas.',
    'Dia 30: Tenho paciência e penso: todo o mal traz consigo algum bem.',
    'Dia 31: O destino não é uma questão de sorte, é uma questão de escolha. Não é algo a se esperar, é algo a se conquistar.'
]

exports.frases = frases;